package projecteuler.projecteuler.problems;

/***
 * Problem statement:
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * 
 * @author Hare Kumar
 *
 */

public class Prob2 {
	
	private final int MAX;
	private int first;
	private int second;
	private int sum;
	
	public Prob2() {
		this.MAX = 4000000;
		this.first = 1;
		this.second = 2;
		this.sum = 0;
	}
	
	public Prob2(int max) {
		this.MAX = max;
		this.first = 1;
		this.second = 2;
		this.sum = 0;
	}
	
	public static void main(String args[]) {
		Prob2 p2 = new Prob2();
		p2.getFibonacciSeries();
	}
	
	private void getFibonacciSeries() {
		
		if(this.first % 2 == 0)
			this.sum += this.first;
		
		if(this.second % 2 == 0) 
			this.sum = this.second;
		
		int next = next(this.first, this.second);
		
		while(next <= MAX) {
			if (next % 2 == 0)
				sum += next;
			
			this.first = this.second;
			this.second = next;
			next = next(this.first, this.second);
		}
		
		System.out.println("Sum is: " + sum);
	}
	
	private int next(int f, int s) {
		return f+s;
		
	}
}
